{% set name = "cmudict" %}
{% set version = "1.0.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmudict-{{ version }}.tar.gz
  sha256: f4c463c8406a2414f9f9058d60e45a7ce69081892ce27102dc91dc1bc6f92115

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - importlib-metadata >=5
    - importlib-resources >=5

test:
  imports:
    - cmudict
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/prosegrinder/python-cmudict
  summary: A versioned python wrapper package for The CMU Pronouncing Dictionary data files.
  license: GPL-3.0-or-later AND BSD-2-Clause
  license_file:
    - LICENSE
    - src/cmudict/data/LICENSE

extra:
  recipe-maintainers:
    - rxm7706
