# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: cmudict
  version: "1.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/cmudict-${{ version }}.tar.gz
  sha256: f6c1cb9a2ffecef387bf1a1b93be6c61c91bc6f41714f183c3eb4d5b3e1ff5f6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - importlib-metadata >=5
    - importlib-resources >=5
    # - importlib_resources >=5
    # - importlib_resources >=5

tests:
  - python:
      imports:
        - cmudict
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: A versioned python wrapper package for The CMU Pronouncing Dictionary data files.
  license: GPL-3.0-or-later AND BSD-2-Clause
  license_file:
    - LICENSE
    - src/cmudict/data/LICENSE
  homepage: https://github.com/prosegrinder/python-cmudict

extra:
  recipe-maintainers:
    - rxm7706
